In [14]:
import os
from PIL import Image
import numpy as np

In [4]:
droot = "/home/sr2/HDD2/Openset/"
sroot = "/home/sr2/Hyeokjun/OOD-saige/datasets/data_split/"

In [6]:
dataset = "Severstal"

In [ ]:
f = open(os.path.join(sroot, dataset, "stats.txt"), 'w')

stats = dict()
for subdir in os.listdir(path.join(droot, dataset)):
    subdir_list = os.listdir(os.path.join(droot, dataset, subdir))
    stats[subdir] = dict()
    stats[subdir]['len'] = 0
    for idx, img in enumerate(subdir_list):
        if 'ipynb' not in img:
            ipath = os.path.join(droot, dataset, subdir, img)
            img = Image.open(ipath)
            if idx == 0:
                stat[subdir]['mean'] = np.zeros(img.shape[2])
                stat[subdir]['sos'] = np.zeros(img.shape[2])
            img = np.asarray(img)
            img = np.reshape(img, (-1, img.shape[2]))
            dim = img.shape[0]
            img = np.array(img, dtype=np.float64)
            img_mean = np.mean(img, axis=0)
            img_sos = np.sum(img**2, axis=0)
            
            stats[subdir]['len'] += 1
            
            cur_mean = stat[subdir]['mean']
            stat[subdir]['mean'] = cur_mean + (img_mean - cur_mean) / stat[subdir]['len']
            
            cur_sos = stat[subdir]['sos']
            stat[subdir]['sos'] += img_sos * dim
            
            
            
            

In [122]:
sample = "/home/sr2/HDD2/Openset/SDI/34Ah/1/0.png"
img = Image.open(sample)
img = np.asarray(img)
img.shape

(256, 256, 3)

In [123]:
img = np.reshape(img, (-1, img.shape[2]))
img = np.array(img, dtype=np.float64)
img[0], (img**2)[0]

(array([134.,  44., 131.]), array([17956.,  1936., 17161.]))

In [124]:
img_mean = np.mean(img, axis=0)
img_std = np.std(img, axis=0)
img_sos = np.sum(img**2, axis=0)
img_sum = np.sum(img, axis=0)
img_mean, img_std, img_sos/(256*256), img_sum/(256 *256)

(array([ 96.21740723,  50.53909302, 128.008255  ]),
 array([43.87085783, 12.60654776,  9.84270404]),
 array([11182.44161987,  2713.12496948, 16482.99217224]),
 array([ 96.21740723,  50.53909302, 128.008255  ]))

In [125]:
img_sos / (256 * 256) - img_mean**2

array([1924.65216647,  158.92504644,   96.87882285])

In [89]:
img_std**2

array([1924.65216647,  158.92504644,   96.87882285])

In [50]:
img_mean + np.zeros(2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [69]:
t = np.ones(3) * 2

In [93]:
np.sum(t**2, axis=0)/3 - np.mean(t)**2

0.0